version: '3'

services:
  openflight_client:
    container_name: openflight_client
    image: node:12
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    command: sh -c '[ ! -d node_modules ] && npm install;npm run serve'
    ports:
      - "8080:8080"
      - "35729:35729"  # for live reload
