version: '3.7'

services:
  openflight_client:
    container_name: openflight_client
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "8080:8080"
      - "35729:35729"  # for live reload
