name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v2
    - name: Build and publish
      uses: docker/build-push-action@v1
      with:
          repository: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          dockerfile: docker/prod.Dockerfile
